spring.application.name=it-the-world-we-built
server.port=8080

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.check-template-location=true

# Static resource handling
spring.web.resources.static-locations=classpath:/static/,classpath:/templates/
